spring:
  application:
    name: api-restfull
    
  datasource:
    username: sa
    password: 123
    url: jdbc:postgresql://localhost:5432/api-restfull-db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update